import Header from './components/Header'
import Logo from './components/Header/Logo'
import Image from 'next/image'
import dino from '../public/dino.jpeg'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  metadataBase: new URL('https://localhost:3000'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: 'https://example.com',
    siteName: 'Example Site',
    images: [
      {
        url: 'https://example.com/ogp.png',
        width: 1260,
        height: 800,
        alt: 'Og Image Alt',
      },
    ],
  }
}

export default function Home() {
  return (
    <>
      <div className="w-[500px] m-3 rounded-lg overflow-hidden">
        <Image src={dino} alt="Dino" />
      </div>
      <Logo />
      <Header quality={1} name={"Nils"} age={35} isMan={true}>
        <p>A message from home</p>
      </Header>
      <main>
        <h1>Main page of my application</h1>
      </main>
    </>
  )
}
